#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2016 Peng Liu <liupeng@imscv.com>
#
# Distributed under terms of the GNU GPL3 license.
"""
This file provides some unchanged contents.
"""


def get_country_dict():
    """
    This function helps generate the unchanged country full name to its abbrev dict.

    :return: the dict which is name -> abbrev.
    """
    pairs = [
        ("United States", "US"),
        ("Afghanistan", "AF"),
        ("Aland Islands", "AX"),
        ("Albania", "AL"),
        ("Algeria", "DZ"),
        ("American Samoa", "AS"),
        ("Andorra", "AD"),
        ("Angola", "AO"),
        ("Anguilla", "AI"),
        ("Antarctica", "AQ"),
        ("Antigua And Barbuda", "AG"),
        ("Argentina", "AR"),
        ("Armenia", "AM"),
        ("Aruba", "AW"),
        ("Australia", "AU"),
        ("Austria", "AT"),
        ("Azerbaijan", "AZ"),
        ("Bahamas", "BS"),
        ("Bahrain", "BH"),
        ("Bangladesh", "BD"),
        ("Barbados", "BB"),
        ("Belarus", "BY"),
        ("Belgium", "BE"),
        ("Belize", "BZ"),
        ("Benin", "BJ"),
        ("Bermuda", "BM"),
        ("Bhutan", "BT"),
        ("Bolivia, Plurinational State Of", "BO"),
        ("Bonaire, Sint Eustatius And Saba", "BQ"),
        ("Bosnia And Herzegovina", "BA"),
        ("Botswana", "BW"),
        ("Bouvet Island", "BV"),
        ("Brazil", "BR"),
        ("British Indian Ocean Territory", "IO"),
        ("Brunei Darussalam", "BN"),
        ("Bulgaria", "BG"),
        ("Burkina Faso", "BF"),
        ("Burundi", "BI"),
        ("Cambodia", "KH"),
        ("Cameroon", "CM"),
        ("Canada", "CA"),
        ("Cape Verde", "CV"),
        ("Cayman Islands", "KY"),
        ("Central African Republic", "CF"),
        ("Chad", "TD"),
        ("Chile", "CL"),
        ("China", "CN"),
        ("Christmas Island", "CX"),
        ("Cocos (Keeling) Islands", "CC"),
        ("Colombia", "CO"),
        ("Comoros", "KM"),
        ("Congo", "CG"),
        ("Congo, The Democratic Republic Of The", "CD"),
        ("Cook Islands", "CK"),
        ("Costa Rica", "CR"),
        ("CÃ´te D'Ivoire", "CI"),
        ("Croatia", "HR"),
        ("CuraÃ§ao", "CW"),
        ("Cuba", "CU"),
        ("Cyprus", "CY"),
        ("Czech Republic", "CZ"),
        ("Denmark", "DK"),
        ("Djibouti", "DJ"),
        ("Dominica", "DM"),
        ("Dominican Republic", "DO"),
        ("Ecuador", "EC"),
        ("Egypt", "EG"),
        ("El Salvador", "SV"),
        ("Equatorial Guinea", "GQ"),
        ("Eritrea", "ER"),
        ("Estonia", "EE"),
        ("Ethiopia", "ET"),
        ("Falkland Islands (Malvinas)", "FK"),
        ("Faroe Islands", "FO"),
        ("Fiji", "FJ"),
        ("Finland", "FI"),
        ("France", "FR"),
        ("French Guiana", "GF"),
        ("French Polynesia", "PF"),
        ("French Southern Territories", "TF"),
        ("Gabon", "GA"),
        ("Gambia", "GM"),
        ("Georgia", "GE"),
        ("Germany", "DE"),
        ("Ghana", "GH"),
        ("Gibraltar", "GI"),
        ("Greece", "GR"),
        ("Greenland", "GL"),
        ("Grenada", "GD"),
        ("Guadeloupe", "GP"),
        ("Guam", "GU"),
        ("Guatemala", "GT"),
        ("Guernsey", "GG"),
        ("Guinea", "GN"),
        ("Guinea-Bissau", "GW"),
        ("Guyana", "GY"),
        ("Haiti", "HT"),
        ("Heard Island And Mcdonald Islands", "HM"),
        ("Holy See (Vatican City State)", "VA"),
        ("Honduras", "HN"),
        ("Hong Kong", "HK"),
        ("Hungary", "HU"),
        ("Iceland", "IS"),
        ("India", "IN"),
        ("Indonesia", "ID"),
        ("Iran, Islamic Republic Of", "IR"),
        ("Iraq", "IQ"),
        ("Ireland", "IE"),
        ("Isle Of Man", "IM"),
        ("Israel", "IL"),
        ("Italy", "IT"),
        ("Jamaica", "JM"),
        ("Japan", "JP"),
        ("Jersey", "JE"),
        ("Jordan", "JO"),
        ("Kazakhstan", "KZ"),
        ("Kenya", "KE"),
        ("Kiribati", "KI"),
        ("Korea, Democratic People'S Republic Of", "KP"),
        ("Korea, Republic Of", "KR"),
        ("Kuwait", "KW"),
        ("Kyrgyzstan", "KG"),
        ("Lao People'S Democratic Republic", "LA"),
        ("Latvia", "LV"),
        ("Lebanon", "LB"),
        ("Lesotho", "LS"),
        ("Liberia", "LR"),
        ("Libyan Arab Jamahiriya", "LY"),
        ("Liechtenstein", "LI"),
        ("Lithuania", "LT"),
        ("Luxembourg", "LU"),
        ("Macao", "MO"),
        ("Macedonia, The Former Yugoslav Republic Of", "MK"),
        ("Madagascar", "MG"),
        ("Malawi", "MW"),
        ("Maldives", "MV"),
        ("Mali", "ML"),
        ("Malta", "MT"),
        ("Marshall Islands", "MH"),
        ("Martinique", "MQ"),
        ("Mauritania", "MR"),
        ("Mauritius", "MU"),
        ("Mayotte", "YT"),
        ("Mexico", "MX"),
        ("Micronesia, Federated States Of", "FM"),
        ("Moldova, Republic Of", "MD"),
        ("Monaco", "MC"),
        ("Mongolia", "MN"),
        ("Montenegro", "ME"),
        ("Montserrat", "MS"),
        ("Morocco", "MA"),
        ("Mozambique", "MZ"),
        ("Myanmar", "MM"),
        ("Namibia", "NA"),
        ("Nauru", "NR"),
        ("Nepal", "NP"),
        ("Netherlands", "NL"),
        ("New Caledonia", "NC"),
        ("New Zealand", "NZ"),
        ("Nicaragua", "NI"),
        ("Niger", "NE"),
        ("Nigeria", "NG"),
        ("Niue", "NU"),
        ("Norfolk Island", "NF"),
        ("Northern Mariana Islands", "MP"),
        ("Norway", "NO"),
        ("Oman", "OM"),
        ("Pakistan", "PK"),
        ("Palau", "PW"),
        ("Palestinian Territory, Occupied", "PS"),
        ("Panama", "PA"),
        ("Papua New Guinea", "PG"),
        ("Paraguay", "PY"),
        ("Peru", "PE"),
        ("Philippines", "PH"),
        ("Pitcairn", "PN"),
        ("Poland", "PL"),
        ("Portugal", "PT"),
        ("Puerto Rico", "PR"),
        ("Qatar", "QA"),
        ("RÃ©union", "RE"),
        ("Romania", "RO"),
        ("Rwanda", "RW"),
        ("Saint BarthÃ©lemy", "BL"),
        ("Saint Helena, Ascension And Tristan Da Cunha", "SH"),
        ("Saint Kitts And Nevis", "KN"),
        ("Saint Lucia", "LC"),
        ("Saint Martin (French Part)", "MF"),
        ("Saint Pierre And Miquelon", "PM"),
        ("Saint Vincent And The Grenadines", "VC"),
        ("Samoa", "WS"),
        ("San Marino", "SM"),
        ("Sao Tome And Principe", "ST"),
        ("Saudi Arabia", "SA"),
        ("Senegal", "SN"),
        ("Serbia", "RS"),
        ("Seychelles", "SC"),
        ("Sierra Leone", "SL"),
        ("Singapore", "SG"),
        ("Sint Maarten (Dutch Part)", "SX"),
        ("Slovakia", "SK"),
        ("Slovenia", "SI"),
        ("Solomon Islands", "SB"),
        ("Somalia", "SO"),
        ("South Africa", "ZA"),
        ("South Georgia And The South Sandwich Islands", "GS"),
        ("South Sudan", "SS"),
        ("Spain", "ES"),
        ("SriLanka", "LK"),
        ("Sudan", "SD"),
        ("Suriname", "SR"),
        ("Svalbard And Jan Mayen", "SJ"),
        ("Swaziland", "SZ"),
        ("Sweden", "SE"),
        ("Switzerland", "CH"),
        ("Syrian Arab Republic", "SY"),
        ("Taiwan, Province Of China", "TW"),
        ("Tajikistan", "TJ"),
        ("Tanzania, United Republic Of", "TZ"),
        ("Thailand", "TH"),
        ("Timor-Leste", "TL"),
        ("Togo", "TG"),
        ("Tokelau", "TK"),
        ("Tonga", "TO"),
        ("Trinidad And Tobago", "TT"),
        ("Tunisia", "TN"),
        ("Turkey", "TR"),
        ("Turkmenistan", "TM"),
        ("Turks And Caicos Islands", "TC"),
        ("Tuvalu", "TV"),
        ("Uganda", "UG"),
        ("Ukraine", "UA"),
        ("United Arab Emirates", "AE"),
        ("United Kingdom", "UK"),
        ("United States", "US"),
        ("United States Minor Outlying Islands", "UM"),
        ("Uruguay", "UY"),
        ("Uzbekistan", "UZ"),
        ("Vanuatu", "VU"),
        ("Venezuela, Bolivarian Republic Of", "VE"),
        ("Viet Nam", "VN"),
        ("Virgin Islands, British", "VG"),
        ("Virgin Islands, U.S.", "VI"),
        ("Wallis And Futuna", "WF"),
        ("Western Sahara", "EH"),
        ("Yemen", "YE"),
        ("Zambia", "ZM"),
        ("Zimbabwe", "ZW"),
    ]
    return dict(pairs)


def get_state_dict():
    """
    This function helps generate state full name to its abbrev dict.

    :return: a dict which maps US state's name to its abbrev.
    """
    pairs = [
        ("Alabama", "AL"),
        ("Alaska", "AK"),
        ("Arizona", "AZ"),
        ("Arkansas", "AR"),
        ("California", "CA"),
        ("Colorado", "CO"),
        ("Connecticut", "CT"),
        ("Delaware", "DE"),
        ("District of Columbia", "DC"),
        ("Florida", "FL"),
        ("Georgia", "GA"),
        ("Hawaii", "HI"),
        ("Idaho", "ID"),
        ("Illinois", "IL"),
        ("Indiana", "IN"),
        ("Iowa", "IA"),
        ("Kansas", "KS"),
        ("Kentucky", "KY"),
        ("Louisiana", "LA"),
        ("Maine", "ME"),
        ("Maryland", "MD"),
        ("Massachusetts", "MA"),
        ("Michigan", "MI"),
        ("Minnesota", "MN"),
        ("Mississippi", "MS"),
        ("Missouri", "MO"),
        ("Montana", "MT"),
        ("Nebraska", "NE"),
        ("Nevada", "NV"),
        ("New Hampshire", "NH"),
        ("New Jersey", "NJ"),
        ("New Mexico", "NM"),
        ("New York", "NY"),
        ("North Carolina", "NC"),
        ("North Dakota", "ND"),
        ("Ohio", "OH"),
        ("Oklahoma", "OK"),
        ("Oregon", "OR"),
        ("Pennsylvania", "PA"),
        ("Puerto Rico", "PR"),
        ("Rhode Island", "RI"),
        ("South Carolina", "SC"),
        ("South Dakota", "SD"),
        ("Tennessee", "TN"),
        ("Texas", "TX"),
        ("Utah", "UT"),
        ("Vermont", "VT"),
        ("Virginia", "VA"),
        ("Virgin Islands", "VI"),
        ("Washington", "WA"),
        ("West Virginia", "WV"),
        ("Wisconsin", "WI"),
        ("Wyoming", "WY"),
    ]
    return dict(pairs)
